In [13]:
def counter(fn):
    cnt = 0
    def inner(*args,**kwargs):
        nonlocal cnt
        cnt += 1
        print("Function called {0} times".format(cnt))
        return fn(*args,**kwargs)
    return inner

In [14]:
@counter
def add(a,b):
    return a+b

In [15]:
add.__doc__

In [3]:
add.__closure__

(<cell at 0x000001BA135D44F0: int object at 0x000001BA0F2E6910>,
 <cell at 0x000001BA135D4130: function object at 0x000001BA135D9550>)

In [6]:
def add(a,b):
    return a+b

In [7]:
add = counter(add)  ## same as using closure

In [8]:
add.__name__

'inner'

In [9]:
from functools import wraps

In [10]:
def counter(fn):
    cnt = 0
    @wraps(fn)
    def inner(*args,**kwargs):
        nonlocal cnt
        cnt += 1
        print("Function called {0} times".format(cnt))
        return fn(*args,**kwargs)
    return inner

In [11]:
@counter
def add(a,b):
    """ Adds 2 nos """
    return a+b

In [12]:
add.__doc__

' Adds 2 nos '

In [16]:
add(2,3)

Function called 1 times


5

In [17]:
from functools import reduce

In [18]:
reduce(lambda x, y: x+y,[1,2,3,4,5])

15

In [26]:
class Fibonacci:
    def __init__(self):
        self.cache = {1:1,2:1}
    def generate_fib(self,n):
        if n not in self.cache:
            print('Enter')
            self.cache[n] = self.generate_fib(n-1) + self.generate_fib(n-2)
        return self.cache[n]

In [27]:
fib = Fibonacci()

In [28]:
fib.generate_fib(10)

Enter
Enter
Enter
Enter
Enter
Enter
Enter
Enter


55

In [29]:
fib.generate_fib(12)

Enter
Enter


144

In [37]:
def fib():
    cache = {1:1,2:1}
    def calc_fib(n):
        nonlocal cache
        if n not in cache:
            print('Enter')
            cache[n] = calc_fib(n-1) + calc_fib(n-2)
        return cache[n]
    return calc_fib

In [38]:
f = fib()

In [39]:
f(10)

Enter
Enter
Enter
Enter
Enter
Enter
Enter
Enter


55

In [40]:
f(12)

Enter
Enter


144

In [41]:
def fib():
    cache = {1:1,2:1}
    def calc_fib(n):
        #nonlocal cache
        if n not in cache:
            print('Enter')
            cache[n] = calc_fib(n-1) + calc_fib(n-2)
        return cache[n]
    return calc_fib

In [42]:
f = fib()

In [43]:
f(12)

Enter
Enter
Enter
Enter
Enter
Enter
Enter
Enter
Enter
Enter


144

In [44]:
f(13)

Enter


233

In [51]:
def counter(fn):
    cnt = 0
    def inner(*args,**kwargs):
        cnt = 0
        cnt = cnt + 1
        print("Function called {0} times".format(cnt))
        return fn(*args,**kwargs)
    return inner

def add(a,b):
    return a+b
def mult(a,b):
    return a*b

In [52]:
add_closure = counter(add)

In [53]:
add_closure(1,2)

Function called 1 times


3

In [54]:
add_closure(1,2)  ## cnt is local variable now

Function called 1 times


3

In [58]:
def counter(fn):
    cnt = []
    def inner(*args,**kwargs):
        cnt.append(fn(*args,**kwargs))
        print("Output {0}".format(cnt))
    return inner

def add(a,b):
    return a+b
def mult(a,b):
    return a*b

In [59]:
add_closure = counter(add)

In [60]:
add_closure(1,2) 

Output [3]


In [61]:
add_closure(1,2) ## if the objet is mutable i think then we dont need nonlocal declaration

Output [3, 3]


In [62]:
def my_dec(a,b): ## parameterized decorator factory
    def dec(fn):
        def inner(*args,**kwargs):
            print("Enter")
            return fn(*args,**kwargs)
        return inner
    return dec

In [63]:
@my_dec(1,2)
def add(a,b):
    return a+b

In [64]:
add(2,3)

Enter


5

In [65]:
def add(a,b):
    return a+b

In [66]:
add.speak = "Rishabh"  ## add attribure to a function, i guess its specific to python only

In [1]:
from numbers import Integral

In [8]:
isinstance(True,Integral)

True

In [10]:
from collections import namedtuple  ## function that generate new class. subclass (inherits from) tuple

In [11]:
a = [1,2,3]

In [12]:
id(a)

2893020506688

In [13]:
a.append(4)

In [14]:
id(a)

2893020506688

In [15]:
a = a+[6]

In [16]:
id(a)

2893021939072

In [17]:
from numpy import random

In [20]:
random.seed(10)

In [21]:
random.randint(1,20,1)

array([10])

In [22]:
random.randint(1,20,1)

array([5])

In [23]:
random.seed(10)
random.randint(1,20,1)

array([10])

In [24]:
from random import seed

In [25]:
seed(100)

In [26]:
random.randint(1,20,1)

array([5])

In [27]:
random.randint(1,20,1)

array([16])

In [28]:
seed(100)
random.randint(1,20,1)

array([1])

In [29]:
seed(100)
random.randint(1,20,1)

array([18])

In [30]:
seed(100)
random.randint(1,20,1)

array([17])

In [ ]:
## random seed while parallelization can be issue if set globally using np.random.seed() as it will take same value
## in call cores and computation will be useless.